services:
  laravel-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../laravel:/var/www/html  # Laravelプロジェクトのパス
    ports:
      - 8080:80
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  mysql-db-data:
